### PR TITLE
this branch fixes/improves on a number of lvalue related issues

### PR DESCRIPTION
**Pull request by leissa**
* fixes issue #45 
* there are now two borrowed pointer types: ```&T``` and ```&mut T```
* the programmer is forced to use the correct address-of prefix expression: ```&e``` vs ```&mut e```

Before we can merge, there are a couple of TODOs:
* port stencilla, imbatracer, fasis etc.

```&e``` is automatically inserted by the compiler if applicable.
```Rust
fn foo(p: &int) -> () {}
fn baz(str: &[u8]) -> () {}

fn bar() -> () {
    let i = 23;
    foo(i);             // instead of foo(&i)
    baz("hello world"); // instead of baz(&"hello world")
}
```
This is the new behaviour regarding mutable references:
```Rust
fn foo(p: &mut int) -> () {}

fn bar() -> () {
    let mut i = 23;
    foo(i);      // error
    foo(&mut i); // ok
}
```

### CODE REVIEW

**Comment by muellan** [comment]
Despite beeing **very** new to impala/anydsl I'd like to comment on that.
You should either always take the address automatically if you supply an argument to a function that has a pointer parameter (like it is done in C++ for references) **regardless** of the mutability or always force the programmer to take the address manually by supplying the appropriate address-of prefix.
Taking the address in case of pointer-to-_non_-mutable automatically but requiring the address-of prefix in case of pointer-to-mutable seems inconsistent and counter-intuitive to me. 

There seems to be no reason the programmer should ever supply a specific version "&mut" vs. "&" of the address operator (you also have only one symbol "&" in C and C++ regardless of mutability of the argument). It just complicates usage and produces noisy code in my opinion. 
Incompatibility between supplying a non-mutable arg to a function expecting a pointer-to-mutable can be checked by the compiler based on the type of the argument.

Personally, I'd prefer to take the address automatically in **all** cases. Like it is done in C++ for references.

**Comment by leissa** [comment]
### Why do you want to have an *explicit* ```&mut expr```:
if you read this code:
```Rust
fn f(p: &mut T) -> () { /*...*/ }

// 1000 lines later or other translation unit:
f(a)
```
you have no idea that ```a``` is being mutated. However, this
```Rust
f(&mut a)
```
makes this explicit and everyone who reads this code will notice that.

C# has btw the same design with the ```ref``` keyword.

The only real argument I see against this is that you spare 4 chars every now and then...

### Why do you want to have an *implicit* ```& expr```:
Coming back to the example:
```Rust
fn f(p: &T) -> () { /*...*/ }

// 1000 lines later or other translation unit:
f(a)
```
Nothing dangerous happens to ```a```. From a semantic point of view it makes no difference if ```f``` takes an imutable reference or a copy.

But I see the point that adding the latter feature seems a bit inconsistent.

**Comment by leissa** [comment]
ah, one addition:
Once we have methods, ```&mut``` is not necessary for the ```self``` argument. For example, this would be fine:
```Rust
foo.mutate_me();
```
Rationale: Anyone reading the code knows, that methods mutate the object. So adding an explicit ```&mut``` to an argument should be a rare case.

**Comment by muellan** [comment]
Hm, I'm not fully convinced of the code readability / documentation argument. In my opinion this is not such a big issue. I have never missed this in C++, but maybe because in modern C++ there are very rare cases where you need out-parameters anyway.
But I can see that others might feel differently about that.

**Comment by leissa** [comment]
>  I have never missed this in C++, but maybe because in modern C++ there are very rare cases where you need out-parameters anyway.

I think that's the point. If you have methods, having additional out parameters is pretty rare. Virtually the only common function I can think of is ```swap```. 

And because additional out parameters are so rare, I think it helps readability to force the user to mark an out-argument. Languages like Rust and C# have good reason for this.

**Comment by leissa** [comment]
implemented codegen for rvalue references

**Comment by madmann91** [comment]
I am for automatically inserting `&` when the reference is taken without mutability. This makes it easier to use strings (i.e. `print("Hello World!")` vs `print(&"Hello World!")`).

**Comment by muellan** [comment]
After having thought about it for a while I now agree that mandating the address-of prefix only in case of pointer-to-mutable parameters might actually be a good decision that balances convenience with code self-documentation. It does make sense, since from the call side it should not matter if the function takes a value or a pointer-to-immutable. And for the less frequent cases that one does require out parameters it might make the code more readable to mandate the address-of-prefix.

**Comment by leissa** [comment]
great, since my vote is also for automatically taking the address of immutable stuff, I'm going to implement that

**Comment by madmann91** [comment]
The behaviour for ++ and -- seems to be broken, because the following piece of code is accepted:

    fn main() -> i32 {
        let mut k = 55;
        (((k++)++)++)++;
        k
    }

I suggest that we stop treating expressions like (++k) or (k++) as lvalues.

**Comment by leissa** [comment]
* implemented: automatically take address of immutable values
* fixed pre/post inc/dec lvalue behavior

**Comment by leissa** [comment]
All codegen tests are working. I'm now waiting for fasis, stencila and imbatracer. Plz report any remaining issues/concerns. From my side, I'm ready to merge.

**Comment by richardmembarth** [comment]
I've updated stincilla, for fasis, I get an infinite loop in InferSema::unify()

One issue I encountered are structs: How should we handle struct members that may be `&mut[T]` or just `&[T]` depending on the context?

For example our `Buffer` struct in https://github.com/AnyDSL/runtime/blob/master/src/runtime.impala
```rust
struct Buffer {
    device: i32,
    data: &[i8]
}
```
For some methods `data` needs to be `&mut[i8]`, for others just `&[i8]`.
Accordingly, all alloc functions should return `&mut[i8]` and copy would require arguments of different type?

How should we handle this?

**Comment by leissa** [comment]
I'll look into the endless loop.

Regarding ```copy```: yes a faithful signature would be:
```Rust
fn copy(dst: &mut[i8], src: &[i8], size: int) -> () { /*...*/ }
```
Unfortunately, we cannot (yet) have a struct member that is polymorphic in its mutability. In the mid-term we can do sth like this:
```Rust
struct Buffer[ptr: type -> type] {
    i32: device,
    data: ptr[[u8]],
}
```
Meanwhile, workarounds would be:
1. define a ```Buffer``` and ```MutBuffer``` struct
2. use some wild casts

I think the first option isn't too much to ask.

To be fair, this whole issue isn't a simple problem in C/C++ either. Anyone who has ever written an iterator which should work as both ```iterator``` and ```const_iterator``` knows, what I'm talking about...

**Comment by leissa** [comment]
@richardmembarth: our fixes for issue #49 also fix the endless loop.

**Comment by richardmembarth** [comment]
Ok, then our codes run on lvalue branch.

**Comment by leissa** [comment]
awesome. may I merge?

**Pull request merged**
