### PR TITLE
Test Suite updated (#5 + #6 + #7)

### PR DESCRIPTION
**Pull request by MasterCassim**
#7 Overwrite tmp files instead of failing
#6 Dumping passed optional tests
#5 Benchmarks ported to test suite

### CODE REVIEW

**Comment by leissa** [comment]
Just tried your work. 

* I get this error:
```
Traceback (most recent call last):
  File "./run_tests.py", line 88, in <module>
    main()
  File "./run_tests.py", line 86, in main
    invoke(executable, directory, valgrind)
  File "./run_tests.py", line 28, in invoke
    infrastructure.tests.executeTests(tests, executable)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/tests.py", line 314, in executeTests
    print("- OPTIONAL test passed: "+test.getName())
AttributeError: 'function' object has no attribute 'getName'
```

* ```run_tests.py``` is not executable anymore. Is that on purpose?

* I don't see any of the new benchmarks actually tested.

**Comment by leissa** [comment]
Oh, and you got your pull request wrong:
```MasterCassim wants to merge 2 commits into master from benchmarks_pr```
I guess you want to merge the other way round :)

Can you plz open a new request? We can continue discussion there.

**Comment by MasterCassim** [comment]
Closed!

**Comment by leissa** [comment]
I still get an error:
```
[320/329] codegen/benchmarks/aobench.impala
Exception in thread Thread-466:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/timed_process.py", line 26, in target
    self.process = subprocess.Popen(self.cmd, cwd=self.cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "./run_tests.py", line 88, in <module>
    main()
  File "./run_tests.py", line 86, in main
    invoke(executable, directory, valgrind)
  File "./run_tests.py", line 28, in invoke
    infrastructure.tests.executeTests(tests, executable)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/tests.py", line 289, in executeTests
    res[tests[i]] = s = tests[i].invoke(gEx)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/tests.py", line 184, in invoke
    p.execute()   
  File "/home/roland/projects/anydsl/impala/test/infrastructure/timed_process.py", line 52, in execute
    self.process.poll()
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by leissa** [comment]
I still get an error:
```
[320/329] codegen/benchmarks/aobench.impala
Exception in thread Thread-466:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/timed_process.py", line 26, in target
    self.process = subprocess.Popen(self.cmd, cwd=self.cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "./run_tests.py", line 88, in <module>
    main()
  File "./run_tests.py", line 86, in main
    invoke(executable, directory, valgrind)
  File "./run_tests.py", line 28, in invoke
    infrastructure.tests.executeTests(tests, executable)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/tests.py", line 289, in executeTests
    res[tests[i]] = s = tests[i].invoke(gEx)
  File "/home/roland/projects/anydsl/impala/test/infrastructure/tests.py", line 184, in invoke
    p.execute()   
  File "/home/roland/projects/anydsl/impala/test/infrastructure/timed_process.py", line 52, in execute
    self.process.poll()
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by MasterCassim** [comment]
My guess is that it is a problem with the llvm installation. Do you have the clang executable at anydsl/llvm_install/bin/clang?

The high numbers are most likely due to the expected output for the benchmark scripts.

**Comment by leissa** [comment]
ah, now we're getting somewhere. For some reasons my system install of clang used to work with the old benchmarks.

**Pull request merged**
