### PR TITLE
SIMD types implementation

### PR DESCRIPTION
**Pull request by madmann91**

### CODE REVIEW

**Comment by madmann91** [comment]
I am currently writing the map expression for vectors. It is not yet pushed because I still have some issues in the code generation part.

**Comment by leissa** [comment]
You will also need the SIMD keyword in the case-definition of EXPR and TYPE in the beginning of parser.cpp.

**Comment by leissa** [comment]
looks good now. Any open issues?

**Comment by madmann91** [comment]
No, not that I can think of. I tested some simple things and it seems to work.

**Pull request merged**
