### PR TITLE
Enums

### PR DESCRIPTION
**Pull request by madmann91**
This branch allows to use enums. Enums are declared with the keyword `enum`:

```rust
enum Test {
    Foo,
    Bar(i32, f32)
}
```

In order to be used, they must be pattern matched:

```rust
let test = Test::Bar(42, 21.0f);
match test {
    Foo => 55,
    Bar(x, _) => x
    _ => // Mandatory, even if the pattern is irrefutable
}
```

There is however a few things to do before merging:
- [ ] Add a few test cases,
- [X] Improve folding of bitcasts in Thorin,
- [ ] Improve type checker so that enums do not require the extra test `_ => /* ... */` when all cases are handled,
- [ ] Add the `Codegen::bitwidth` function to Thorin.

### CODE REVIEW

**Comment by richardmembarth** [comment]
I created a branch enums for Stincilla using enums for the boundary handling logic.
https://github.com/AnyDSL/stincilla/tree/enums

This triggers an assertion in Impala:
```
impala/src/impala/ast.h:560: bool impala::Decl::is_mut() const: Assertion `is_value_decl()' failed.
```

**Comment by richardmembarth** [comment]
Is it also possible to compare enum values directly, for example:
```Rust
if mode == Boundary::Center { ... }
```
Instead we need to use match:
```Rust
match mode {
  Boundary::Center => ...
  _ => ...
}
```

**Comment by leissa** [comment]
I think it would be also fine to merge this like this into master. The remaining issues can be fixed later on. -- Unless you have objections, of course.

**Comment by madmann91** [comment]
There are still many problems here.
 - The type system is not cleaned up.
 - LLVM does not support casting between aggregates and I think we need to implement a simple form of variants in Thorin.
 - Type inference bugs are still present

Regarding @richardmembarth's comment: We might implement that in the future, similarly to the `if let` construct of Rust (https://rustbyexample.com/flow_control/if_let.html).

**Pull request merged**
